[2018-11-20T12:26:46.339] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":"TypeError: result.populate(...).exec is not a function"}
[2018-11-20T12:42:38.310] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":"ReferenceError: result_1 is not defined"}
[2018-11-20T13:20:54.442] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":"SyntaxError: Unexpected identifier"}
